services:
  go-app:
    container_name: image-extractor-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    # volumes:
    #   - ./:/app
    networks:
      - go-network
  
networks:
  go-network:
    driver: bridge
    